language: python
python:
- '3.4'
sudo: false
install:
  - pip3 install codecov gpiozero
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - coverage run  -m unittest discover -s test
after_success:
  - codecov
deploy:
  provider: pypi
  user: waynek
  password:
    secure: YwJFPUt9lop1SYMaPu0ZQIX+4REqcv3gnopgqOvqUKe6HVUticg6OW4hmH0sYfVVJEwT71jkv+HWkQAOPeN7PTjB7ErhG/wcdYzfyw3il3+96usO1Yfb/huZPed/NQ87t8TMe1FpeS4e5TZISAcwEeVP34lX2y//FSD+zVDYu9EOWhTmOKy1qrjJaWGBsUG3et3zkgwKKI9uIbp7uekQxlU/5AXMqwFCf7uto3t9odYB3CCC1oQD4X0fEAIWYJEAbwq4XRijvkmciu58JNkDCLF58nHwXtgKyu0dAVrZbF5x+9mBdZ861gxVWX7d1PlvXK/NIcFMntnOgKAM9FKNZXQkFl/85lbeHrL8D+OrXwqKMUKG8aN3FZ2WsvQ9bDm8XTQ9feIw5zrUpdoqBgZQlgBFSNTajR7Vg4t8X/FIBphQOTRfbMa4z9KitSdS6cIfDjmaatQ6iyqO+GEtAg3BqrXZfcROccbjpEcYaZIqzIe43Xs2x/UWDbVZmcEqmi9P2lVqe4B7h2NF/gVHRiVXAA1azERIbXlo9dFwT3XnaRVVPvaPQYyfG48oYOcNvfAQ0Vn0bBkAFaNp7Ukji8U5UXV6lKbkOU/hQWJtqzAdvYt95QW/pkYxQELp9yJtIaxxLc3XfTzeQe5PJjGIkij74oeUdZBEkZFEUKegnmdKpT4=
  on:
      tags: true

addons:
  sauce_connect:
    username: waynekeenan
  jwt:
    secure: XoKNopVgb+mje9kcNswENgqZSMbXBDuYoCzePgdNq+6Asz5ydoVD6Hn6HFxRkUSB26AjOWB8CbytAqpIxgMvM7JVRGAmgpsSDQLJhCafA5Q5HMa0SJeRj9BruYeitGfWd0jpKCnqAwj71wT1W0eQHiSOOlwNwrYS/aBmMGjr8d01e0OLnuO0ZjcJLzapzfxxheDRh2u3UxG/IHMTI/rlus/N5+peetoPEShKtIIjuA4Hta1q2npI/OS+rZOdrCVRhu+Z/tzJ21vFh9BNidZ3RbIzlBuotmN4h9zPzfxEBHn/W6JFSvmFVZqGmkzDb4TiAdUNPZ8nM2wfxzG4qR0Ut34Ro++5QwfP+HuP4iVzl+U4tnJ+pf5w4QB4QDYXjcFpK+FiOKOOKkNCRW30rftkAq7nHInyK/GuIp8BuEmXBc3bmiM3RF5yu4VxOsPxOOw8Uc1kiWbCui6ut2uA3mytYzEvhN44HOR6z7im/vIVg0mCuCpCQ6YbVtlyYGoOW9pUuH8vYGMZR65n0mZvwq81SIGxo8hbQr4L01qWcKzsZJbLrSXdLr/dClLFyjrcR8wtMcl14vhd6yH/P74M7ioAyKPce26D1Xc5U8ra6yan99lEEcBX/MLC/zseSbykllL70f2eYL09RV7t7Ge7SJo4tPN+JRWNyFnJ6UDtlaj6cHI=
